sudo: required
dist: xenial
dotnet: 2.2
language: csharp
mono: none

os:
  - linux
  - osx

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - NUGET_XMLDOC_MODE=skip

branches:
  only:
    - master

addons:
  apt:
    packages:
    - gettext
    - google-chrome-stable
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    sources:
    - google-chrome

install:
  - npm install --global bower
  - npm install --global npm

script:
  - ./build.sh
