os: Visual Studio 2017
version: 3.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

install:
  - ps: npm install -g bower@1.8.0 --loglevel=error
  - ps: npm install -g npm

build_script:
  - ps: .\Build.ps1

skip_tags: false
test: off
